# -*- coding: utf-8 -*-
"""Production registry of explicitly verified Annex 1 semantic nodes.

The entries in VERIFIED_SEMANTICS were moved unchanged from the semantic
inventory test after the full 188-node inventory reached Behavioral PASS.
"""

from __future__ import annotations

from law_data.building_use_annex1_semantic_model import (
    ACTIVE,
    DELETED,
    UNRESOLVED,
    USE,
    MULTI_USE,
    CATEGORY,
    QUALIFICATION,
    SIMILAR_USE,
    OTHER_USE,
    ANCILLARY_USE,
    DELETED_ROLE,
    UNRESOLVED_ROLE,
    BuildingUseSemanticNode,
    SourcePath,
)


VERIFIED_SEMANTICS: dict[str, BuildingUseSemanticNode] = {
    "1": BuildingUseSemanticNode(SourcePath("1"), ACTIVE, CATEGORY, "단독주택"),
    "2": BuildingUseSemanticNode(SourcePath("2"), ACTIVE, CATEGORY, "공동주택"),
    "3": BuildingUseSemanticNode(SourcePath("3"), ACTIVE, CATEGORY, "제1종 근린생활시설"),
    "4": BuildingUseSemanticNode(SourcePath("4"), ACTIVE, CATEGORY, "제2종 근린생활시설"),
    "5": BuildingUseSemanticNode(SourcePath("5"), ACTIVE, CATEGORY, "문화 및 집회시설"),
    "6": BuildingUseSemanticNode(SourcePath("6"), ACTIVE, CATEGORY, "종교시설"),
    "7": BuildingUseSemanticNode(SourcePath("7"), ACTIVE, CATEGORY, "판매시설"),
    "11": BuildingUseSemanticNode(SourcePath("11"), ACTIVE, CATEGORY, "노유자시설"),
    "12": BuildingUseSemanticNode(SourcePath("12"), ACTIVE, CATEGORY, "수련시설"),
    "13": BuildingUseSemanticNode(SourcePath("13"), ACTIVE, CATEGORY, "운동시설"),
    "14": BuildingUseSemanticNode(SourcePath("14"), ACTIVE, CATEGORY, "업무시설"),
    "15": BuildingUseSemanticNode(SourcePath("15"), ACTIVE, CATEGORY, "숙박시설"),
    "16": BuildingUseSemanticNode(SourcePath("16"), ACTIVE, CATEGORY, "위락시설"),
    "19": BuildingUseSemanticNode(SourcePath("19"), ACTIVE, CATEGORY, "위험물 저장 및 처리 시설"),
    "23": BuildingUseSemanticNode(SourcePath("23"), ACTIVE, CATEGORY, "교정시설"),
    "1/가": BuildingUseSemanticNode(SourcePath("1", "가"), ACTIVE, USE, "단독주택"),
    "1/라": BuildingUseSemanticNode(SourcePath("1", "라"), ACTIVE, USE, "공관"),
    "4/다": BuildingUseSemanticNode(SourcePath("4", "다"), ACTIVE, USE, "자동차영업소"),
    "4/라": BuildingUseSemanticNode(SourcePath("4", "라"), ACTIVE, USE, "서점"),
    "4/마": BuildingUseSemanticNode(SourcePath("4", "마"), ACTIVE, USE, "총포판매소"),
    "4/자": BuildingUseSemanticNode(SourcePath("4", "자"), ACTIVE, USE, "일반음식점"),
    "4/거": BuildingUseSemanticNode(SourcePath("4", "거"), ACTIVE, USE, "다중생활시설"),
    "4/더": BuildingUseSemanticNode(SourcePath("4", "더"), ACTIVE, USE, "단란주점"),
    "4/머": BuildingUseSemanticNode(SourcePath("4", "머"), ACTIVE, USE, "주문배송시설"),
    "4/버": BuildingUseSemanticNode(SourcePath("4", "버"), ACTIVE, USE, "공유보관시설"),
    "5/가": BuildingUseSemanticNode(SourcePath("5", "가"), ACTIVE, USE, "공연장"),
    "5/나": BuildingUseSemanticNode(SourcePath("5", "나"), ACTIVE, USE, "집회장"),
    "5/다": BuildingUseSemanticNode(SourcePath("5", "다"), ACTIVE, USE, "관람장"),
    "5/라": BuildingUseSemanticNode(SourcePath("5", "라"), ACTIVE, USE, "전시장"),
    "5/마": BuildingUseSemanticNode(SourcePath("5", "마"), ACTIVE, USE, "동·식물원"),
    "6/가": BuildingUseSemanticNode(SourcePath("6", "가"), ACTIVE, USE, "종교집회장"),
    "7/가": BuildingUseSemanticNode(SourcePath("7", "가"), ACTIVE, USE, "도매시장"),
    "7/나": BuildingUseSemanticNode(SourcePath("7", "나"), ACTIVE, USE, "소매시장"),
    "12/다": BuildingUseSemanticNode(SourcePath("12", "다"), ACTIVE, USE, "유스호스텔"),
    "14/가": BuildingUseSemanticNode(SourcePath("14", "가"), ACTIVE, USE, "공공업무시설"),
    "15/다": BuildingUseSemanticNode(SourcePath("15", "다"), ACTIVE, USE, "다중생활시설"),
    "16/바": BuildingUseSemanticNode(SourcePath("16", "바"), ACTIVE, USE, "카지노영업소"),
    "15/나": BuildingUseSemanticNode(SourcePath("15", "나"), ACTIVE, USE, "관광숙박시설"),
    "19/사": BuildingUseSemanticNode(SourcePath("19", "사"), ACTIVE, USE, "도료류 판매소"),
    "19/아": BuildingUseSemanticNode(SourcePath("19", "아"), ACTIVE, USE, "도시가스 제조시설"),
    "19/자": BuildingUseSemanticNode(SourcePath("19", "자"), ACTIVE, USE, "화약류 저장소"),
    "4/바": BuildingUseSemanticNode(SourcePath("4", "바"), ACTIVE, MULTI_USE),
    "4/러": BuildingUseSemanticNode(SourcePath("4", "러"), ACTIVE, MULTI_USE),
    "4/타": BuildingUseSemanticNode(SourcePath("4", "타"), ACTIVE, MULTI_USE),
    "10/라": BuildingUseSemanticNode(SourcePath("10", "라"), ACTIVE, MULTI_USE),
    "15/가": BuildingUseSemanticNode(SourcePath("15", "가"), ACTIVE, MULTI_USE),
    "16/마": BuildingUseSemanticNode(SourcePath("16", "마"), ACTIVE, MULTI_USE),
    "19/가": BuildingUseSemanticNode(SourcePath("19", "가"), ACTIVE, MULTI_USE),
    "19/나": BuildingUseSemanticNode(SourcePath("19", "나"), ACTIVE, MULTI_USE),
    "19/다": BuildingUseSemanticNode(SourcePath("19", "다"), ACTIVE, MULTI_USE),
    "19/라": BuildingUseSemanticNode(SourcePath("19", "라"), ACTIVE, MULTI_USE),
    "19/바": BuildingUseSemanticNode(SourcePath("19", "바"), ACTIVE, MULTI_USE),
    "23/다": BuildingUseSemanticNode(SourcePath("23", "다"), ACTIVE, MULTI_USE),
    "26/라": BuildingUseSemanticNode(SourcePath("26", "라"), ACTIVE, MULTI_USE),
    "3/마": BuildingUseSemanticNode(SourcePath("3", "마"), ACTIVE, MULTI_USE),
    "3/카": BuildingUseSemanticNode(SourcePath("3", "카"), ACTIVE, MULTI_USE),
    "4/차": BuildingUseSemanticNode(SourcePath("4", "차"), ACTIVE, MULTI_USE),
    "4/파": BuildingUseSemanticNode(SourcePath("4", "파"), ACTIVE, MULTI_USE),
    "13/가": BuildingUseSemanticNode(SourcePath("13", "가"), ACTIVE, MULTI_USE),
    "3/가": BuildingUseSemanticNode(SourcePath("3", "가"), ACTIVE, USE, "소매점"),
    "3/차": BuildingUseSemanticNode(SourcePath("3", "차"), ACTIVE, USE, "전기자동차 충전소"),
    "6/나": BuildingUseSemanticNode(SourcePath("6", "나"), ACTIVE, USE, "봉안당"),
    "7/다": BuildingUseSemanticNode(SourcePath("7", "다"), ACTIVE, USE, "상점"),
    "14/나": BuildingUseSemanticNode(SourcePath("14", "나"), ACTIVE, USE, "일반업무시설"),
    "3/나": BuildingUseSemanticNode(SourcePath("3", "나"), ACTIVE, MULTI_USE),
    "4/아": BuildingUseSemanticNode(SourcePath("4", "아"), ACTIVE, MULTI_USE),
    "3/자": BuildingUseSemanticNode(SourcePath("3", "자"), ACTIVE, MULTI_USE),
    "4/하": BuildingUseSemanticNode(SourcePath("4", "하"), ACTIVE, MULTI_USE),
    "14/나/1": BuildingUseSemanticNode(SourcePath("14", "나", 1), ACTIVE, MULTI_USE),
    "3/바": BuildingUseSemanticNode(SourcePath("3", "바"), ACTIVE, MULTI_USE),
    "3/아": BuildingUseSemanticNode(SourcePath("3", "아"), ACTIVE, MULTI_USE),
    "4/카": BuildingUseSemanticNode(SourcePath("4", "카"), ACTIVE, MULTI_USE),
    "4/너": BuildingUseSemanticNode(SourcePath("4", "너"), ACTIVE, MULTI_USE),
    "19/마": BuildingUseSemanticNode(SourcePath("19", "마"), ACTIVE, USE, "유독물 보관·저장·판매시설"),
    "3/사": BuildingUseSemanticNode(SourcePath("3", "사"), ACTIVE, MULTI_USE),
    "4/사": BuildingUseSemanticNode(SourcePath("4", "사"), ACTIVE, MULTI_USE),
    "8/바": BuildingUseSemanticNode(SourcePath("8", "바"), ACTIVE, SIMILAR_USE),
    "11/다": BuildingUseSemanticNode(SourcePath("11", "다"), ACTIVE, OTHER_USE),
    "15/라": BuildingUseSemanticNode(SourcePath("15", "라"), ACTIVE, SIMILAR_USE),
    "19/차": BuildingUseSemanticNode(SourcePath("19", "차"), ACTIVE, SIMILAR_USE),
    "21/아": BuildingUseSemanticNode(SourcePath("21", "아"), ACTIVE, SIMILAR_USE),
    "24/바": BuildingUseSemanticNode(SourcePath("24", "바"), ACTIVE, SIMILAR_USE),
    "26/다": BuildingUseSemanticNode(SourcePath("26", "다"), ACTIVE, ANCILLARY_USE),
    "27/바": BuildingUseSemanticNode(SourcePath("27", "바"), ACTIVE, ANCILLARY_USE),
    "3/다": BuildingUseSemanticNode(SourcePath("3", "다"), ACTIVE, MULTI_USE),
    "3/라": BuildingUseSemanticNode(SourcePath("3", "라"), ACTIVE, MULTI_USE),
    "11/가": BuildingUseSemanticNode(SourcePath("11", "가"), ACTIVE, USE, "아동 관련 시설"),
    "11/나": BuildingUseSemanticNode(SourcePath("11", "나"), ACTIVE, USE, "노인복지시설"),
    "12/가": BuildingUseSemanticNode(SourcePath("12", "가"), ACTIVE, USE, "생활권 수련시설"),
    "12/나": BuildingUseSemanticNode(SourcePath("12", "나"), ACTIVE, USE, "자연권 수련시설"),
    "16/나": BuildingUseSemanticNode(SourcePath("16", "나"), ACTIVE, USE, "유흥주점"),
    "16/다": BuildingUseSemanticNode(SourcePath("16", "다"), ACTIVE, USE, "테마파크업의 시설"),
    "23/가": BuildingUseSemanticNode(SourcePath("23", "가"), ACTIVE, USE, "교정시설"),
    "23/나": BuildingUseSemanticNode(SourcePath("23", "나"), ACTIVE, USE, "갱생보호시설"),
    "4/가": BuildingUseSemanticNode(SourcePath("4", "가"), ACTIVE, USE, "공연장"),
    "4/나": BuildingUseSemanticNode(SourcePath("4", "나"), ACTIVE, USE, "종교집회장"),
    "12/라": BuildingUseSemanticNode(SourcePath("12", "라"), ACTIVE, USE, "야영장 시설"),
    "13/나": BuildingUseSemanticNode(SourcePath("13", "나"), ACTIVE, USE, "체육관"),
    "13/다": BuildingUseSemanticNode(SourcePath("13", "다"), ACTIVE, USE, "운동장"),
    "16/가": BuildingUseSemanticNode(SourcePath("16", "가"), ACTIVE, USE, "단란주점"),
    "1/나": BuildingUseSemanticNode(SourcePath("1", "나"), ACTIVE, USE, "다중주택"),
    "1/나/1": BuildingUseSemanticNode(SourcePath("1", "나", 1), ACTIVE, QUALIFICATION),
    "1/나/2": BuildingUseSemanticNode(SourcePath("1", "나", 2), ACTIVE, QUALIFICATION),
    "1/나/3": BuildingUseSemanticNode(SourcePath("1", "나", 3), ACTIVE, QUALIFICATION),
    "1/나/4": BuildingUseSemanticNode(SourcePath("1", "나", 4), ACTIVE, QUALIFICATION),
    "1/다": BuildingUseSemanticNode(SourcePath("1", "다"), ACTIVE, USE, "다가구주택"),
    "1/다/1": BuildingUseSemanticNode(SourcePath("1", "다", 1), ACTIVE, QUALIFICATION),
    "1/다/2": BuildingUseSemanticNode(SourcePath("1", "다", 2), ACTIVE, QUALIFICATION),
    "1/다/3": BuildingUseSemanticNode(SourcePath("1", "다", 3), ACTIVE, QUALIFICATION),
    "2/라/2": BuildingUseSemanticNode(SourcePath("2", "라", 2), ACTIVE, USE, "임대형기숙사"),
    "2/가": BuildingUseSemanticNode(SourcePath("2", "가"), ACTIVE, USE, "아파트"),
    "2/나": BuildingUseSemanticNode(SourcePath("2", "나"), ACTIVE, USE, "연립주택"),
    "2/다": BuildingUseSemanticNode(SourcePath("2", "다"), ACTIVE, USE, "다세대주택"),
    "2/라": BuildingUseSemanticNode(SourcePath("2", "라"), ACTIVE, USE, "기숙사"),
    "2/라/1": BuildingUseSemanticNode(SourcePath("2", "라", 1), ACTIVE, USE, "일반기숙사"),
    "4/너/1": BuildingUseSemanticNode(SourcePath("4", "너", 1), ACTIVE, QUALIFICATION),
    "4/너/2": BuildingUseSemanticNode(SourcePath("4", "너", 2), ACTIVE, QUALIFICATION),
    "7/다/1": BuildingUseSemanticNode(SourcePath("7", "다", 1), ACTIVE, QUALIFICATION),
    "7/다/2": BuildingUseSemanticNode(SourcePath("7", "다", 2), ACTIVE, QUALIFICATION),
    "16/라": BuildingUseSemanticNode(SourcePath("16", "라"), DELETED, DELETED_ROLE),
    "17": BuildingUseSemanticNode(SourcePath("17"), ACTIVE, USE, "공장"),
    "25": BuildingUseSemanticNode(SourcePath("25"), ACTIVE, USE, "발전시설"),
    "29": BuildingUseSemanticNode(SourcePath("29"), ACTIVE, USE, "야영장 시설"),
    "8": BuildingUseSemanticNode(SourcePath("8"), ACTIVE, CATEGORY, "운수시설"),
    "8/가": BuildingUseSemanticNode(SourcePath("8", "가"), ACTIVE, USE, "여객자동차터미널"),
    "8/나": BuildingUseSemanticNode(SourcePath("8", "나"), ACTIVE, USE, "철도시설"),
    "8/다": BuildingUseSemanticNode(SourcePath("8", "다"), ACTIVE, USE, "공항시설"),
    "8/라": BuildingUseSemanticNode(SourcePath("8", "라"), ACTIVE, USE, "항만시설"),
    "8/마": BuildingUseSemanticNode(SourcePath("8", "마"), ACTIVE, USE, "버티포트"),
    "9/가": BuildingUseSemanticNode(SourcePath("9", "가"), ACTIVE, USE, "병원"),
    "9/나": BuildingUseSemanticNode(SourcePath("9", "나"), ACTIVE, USE, "격리병원"),
    "10/가": BuildingUseSemanticNode(SourcePath("10", "가"), ACTIVE, USE, "학교"),
    "10/나": BuildingUseSemanticNode(SourcePath("10", "나"), ACTIVE, USE, "교육원"),
    "10/다": BuildingUseSemanticNode(SourcePath("10", "다"), ACTIVE, USE, "직업훈련소"),
    "10/마": BuildingUseSemanticNode(SourcePath("10", "마"), ACTIVE, USE, "연구소"),
    "10/바": BuildingUseSemanticNode(SourcePath("10", "바"), ACTIVE, USE, "도서관"),

    "9": BuildingUseSemanticNode(SourcePath("9"), ACTIVE, CATEGORY, "의료시설"),
    "10": BuildingUseSemanticNode(SourcePath("10"), ACTIVE, CATEGORY, "교육연구시설"),
    "18": BuildingUseSemanticNode(SourcePath("18"), ACTIVE, CATEGORY, "창고시설"),
    "18/가": BuildingUseSemanticNode(SourcePath("18","가"), ACTIVE, USE, "창고"),
    "18/나": BuildingUseSemanticNode(SourcePath("18","나"), ACTIVE, USE, "하역장"),
    "18/다": BuildingUseSemanticNode(SourcePath("18","다"), ACTIVE, USE, "물류터미널"),
    "18/라": BuildingUseSemanticNode(SourcePath("18","라"), ACTIVE, USE, "집배송 시설"),
    "20/가": BuildingUseSemanticNode(SourcePath("20","가"), ACTIVE, USE, "주차장"),
    "20/나": BuildingUseSemanticNode(SourcePath("20","나"), ACTIVE, USE, "세차장"),
    "20/다": BuildingUseSemanticNode(SourcePath("20","다"), ACTIVE, USE, "폐차장"),
    "20/라": BuildingUseSemanticNode(SourcePath("20","라"), ACTIVE, USE, "검사장"),
    "20/마": BuildingUseSemanticNode(SourcePath("20","마"), ACTIVE, USE, "매매장"),
    "20/바": BuildingUseSemanticNode(SourcePath("20","바"), ACTIVE, USE, "정비공장"),
    "20/사": BuildingUseSemanticNode(SourcePath("20","사"), ACTIVE, USE, "운전학원 및 정비학원"),
    "20/아": BuildingUseSemanticNode(SourcePath("20","아"), ACTIVE, USE, "차고 및 주기장"),
    "20/자": BuildingUseSemanticNode(SourcePath("20","자"), ACTIVE, USE, "전기자동차 충전소"),
    "21/가": BuildingUseSemanticNode(SourcePath("21","가"), ACTIVE, USE, "축사"),
    "21/나": BuildingUseSemanticNode(SourcePath("21","나"), ACTIVE, USE, "가축시설"),
    "21/다": BuildingUseSemanticNode(SourcePath("21","다"), ACTIVE, USE, "도축장"),
    "21/라": BuildingUseSemanticNode(SourcePath("21","라"), ACTIVE, USE, "도계장"),
    "21/마": BuildingUseSemanticNode(SourcePath("21","마"), ACTIVE, USE, "작물 재배사"),
    "21/바": BuildingUseSemanticNode(SourcePath("21","바"), ACTIVE, USE, "종묘배양시설"),
    "21/사": BuildingUseSemanticNode(SourcePath("21","사"), ACTIVE, USE, "온실"),
    "22/가": BuildingUseSemanticNode(SourcePath("22","가"), ACTIVE, USE, "하수 등 처리시설"),
    "22/나": BuildingUseSemanticNode(SourcePath("22","나"), ACTIVE, USE, "고물상"),
    "22/다": BuildingUseSemanticNode(SourcePath("22","다"), ACTIVE, USE, "폐기물재활용시설"),
    "22/라": BuildingUseSemanticNode(SourcePath("22","라"), ACTIVE, USE, "폐기물 처분시설"),
    "22/마": BuildingUseSemanticNode(SourcePath("22","마"), ACTIVE, USE, "폐기물감량화시설"),
    "24/가": BuildingUseSemanticNode(SourcePath("24","가"), ACTIVE, USE, "방송국"),
    "24/나": BuildingUseSemanticNode(SourcePath("24","나"), ACTIVE, USE, "전신전화국"),
    "24/다": BuildingUseSemanticNode(SourcePath("24","다"), ACTIVE, USE, "촬영소"),
    "24/라": BuildingUseSemanticNode(SourcePath("24","라"), ACTIVE, USE, "통신용 시설"),
    "24/마": BuildingUseSemanticNode(SourcePath("24","마"), ACTIVE, USE, "데이터센터"),
    "26/가": BuildingUseSemanticNode(SourcePath("26","가"), ACTIVE, USE, "화장시설"),
    "26/나": BuildingUseSemanticNode(SourcePath("26","나"), ACTIVE, USE, "봉안당"),
    "27/가": BuildingUseSemanticNode(SourcePath("27","가"), ACTIVE, USE, "야외음악당"),
    "27/나": BuildingUseSemanticNode(SourcePath("27","나"), ACTIVE, USE, "야외극장"),
    "27/다": BuildingUseSemanticNode(SourcePath("27","다"), ACTIVE, USE, "어린이회관"),
    "27/라": BuildingUseSemanticNode(SourcePath("27","라"), ACTIVE, USE, "관망탑"),
    "27/마": BuildingUseSemanticNode(SourcePath("27","마"), ACTIVE, USE, "휴게소"),
    "28/가": BuildingUseSemanticNode(SourcePath("28","가"), ACTIVE, USE, "장례식장"),
    "28/나": BuildingUseSemanticNode(SourcePath("28","나"), ACTIVE, USE, "동물 전용의 장례식장"),

    "20": BuildingUseSemanticNode(SourcePath("20"), ACTIVE, CATEGORY, "자동차 관련 시설"),
    "21": BuildingUseSemanticNode(SourcePath("21"), ACTIVE, CATEGORY, "동물 및 식물 관련 시설"),
    "22": BuildingUseSemanticNode(SourcePath("22"), ACTIVE, CATEGORY, "자원순환 관련 시설"),
    "24": BuildingUseSemanticNode(SourcePath("24"), ACTIVE, CATEGORY, "방송통신시설"),
    "26": BuildingUseSemanticNode(SourcePath("26"), ACTIVE, CATEGORY, "묘지 관련 시설"),
    "27": BuildingUseSemanticNode(SourcePath("27"), ACTIVE, CATEGORY, "관광 휴게시설"),
    "28": BuildingUseSemanticNode(SourcePath("28"), ACTIVE, CATEGORY, "장례시설"),
    "14/나/2": BuildingUseSemanticNode(SourcePath("14", "나", 2), ACTIVE, USE, "오피스텔"),
    "23/라": BuildingUseSemanticNode(SourcePath("23", "라"), DELETED, DELETED_ROLE),
    "23의2": BuildingUseSemanticNode(SourcePath("23의2"), ACTIVE, USE, "국방ㆍ군사시설"),
}
