"""STEP54 immutable execution package before any Rule Engine behavioral consumption."""
from __future__ import annotations
import copy
from dataclasses import dataclass
from typing import Any, Mapping
from law_data.historical_site_event_rule_engine_consumption_preview_authorization import BOUNDARY_NAME as AUTH_BOUNDARY_NAME, HistoricalSiteEventRuleEngineConsumptionPreviewAuthorization
from law_data.historical_site_event_site_registry_mutation_executor import BOUNDARY_NAME as EXEC_BOUNDARY_NAME, HistoricalSiteEventSiteRegistryMutationExecution
BOUNDARY_NAME="HISTORICAL_SITE_EVENT_RULE_ENGINE_CONSUMPTION_EXECUTION_PACKAGE"
@dataclass(frozen=True)
class HistoricalSiteEventRuleEngineConsumptionExecutionPackage:
    boundary:str; authorization_present:bool; authorization_boundary_matched:bool; rule_engine_consumption_authorized:bool; execution_present:bool; execution_boundary_matched:bool; mutation_executed:bool; condition_identity_matched:bool; committed_registry_present:bool; authorized_repair_count:int; affected_rule_indexes:tuple[int,...]; expected_refresh_rule_count:int; no_op_consumption:bool; execution_mode:str; missing_gates:tuple[str,...]; rule_engine_consumption_execution_package_ready:bool; packaged_registry:Mapping[str,Mapping[str,Any]]; packaged_historical_condition:Mapping[str,Any]; packaged_repairs:tuple[Mapping[str,Any],...]
    def to_dict(self):
        return {**self.__dict__,"affected_rule_indexes":list(self.affected_rule_indexes),"missing_gates":list(self.missing_gates),"packaged_registry":copy.deepcopy(dict(self.packaged_registry)),"packaged_historical_condition":copy.deepcopy(dict(self.packaged_historical_condition)),"packaged_repairs":copy.deepcopy(list(self.packaged_repairs)),"apply_site_registry_called":False,"refresh_rule_called":False,"rules_mutated":False,"rule_engine_state_mutated":False,"rule_evaluation_executed":False,"rule_applicability_recalculated":False,"rule_applicability_changed":False,"site_analysis_builder_modified":False,"production_wiring_applied":False,"runtime_registered":False,"public_api_exposed":False}
def package_historical_site_event_rule_engine_consumption_execution(authorization:HistoricalSiteEventRuleEngineConsumptionPreviewAuthorization|None, execution:HistoricalSiteEventSiteRegistryMutationExecution|None):
    ap=isinstance(authorization,HistoricalSiteEventRuleEngineConsumptionPreviewAuthorization); ab=bool(ap and authorization.boundary==AUTH_BOUNDARY_NAME); aa=bool(ap and authorization.rule_engine_consumption_authorized is True); ep=isinstance(execution,HistoricalSiteEventSiteRegistryMutationExecution); eb=bool(ep and execution.boundary==EXEC_BOUNDARY_NAME); me=bool(ep and execution.mutation_executed is True); an=str(authorization.historical_condition_name or "").strip() if ap else ""; en=str(execution.committed_historical_condition_name or "").strip() if ep else ""; identity=bool(an and an==en); registry=copy.deepcopy(dict(execution.committed_registry)) if ep else {}; condition=copy.deepcopy(dict(execution.committed_historical_condition)) if ep else {}; repairs=copy.deepcopy(tuple(authorization.authorized_repairs)) if ap else (); indexes=tuple(sorted({r["rule_index"] for r in repairs if isinstance(r,Mapping) and r.get("would_change") is True and isinstance(r.get("rule_index"),int)})); expected=authorization.expected_refresh_rule_count if ap else 0; noop=bool(ap and authorization.no_op_consumption is True); mode="NO_OP" if noop else "CHANGED_TARGETS"; repair_alignment=bool(ap and len(repairs)==authorization.repair_count and len(indexes)==authorization.affected_rule_count==expected); registry_alignment=bool(identity and isinstance(registry.get(en),Mapping) and dict(registry[en])==condition); mode_alignment=bool((noop and not repairs and expected==0) or (not noop and expected>0 and bool(repairs)))
    gates=(("authorization_present",ap),("authorization_boundary_matched",ab),("rule_engine_consumption_authorized",aa),("execution_present",ep),("execution_boundary_matched",eb),("mutation_executed",me),("condition_identity_matched",identity),("committed_registry_present",bool(registry)),("repair_alignment",repair_alignment),("registry_alignment",registry_alignment),("execution_mode_aligned",mode_alignment)); missing=tuple(g for g,p in gates if not p); ready=not missing
    return HistoricalSiteEventRuleEngineConsumptionExecutionPackage(BOUNDARY_NAME,ap,ab,aa,ep,eb,me,identity,bool(registry),len(repairs),indexes,expected,noop,mode,missing,ready,(registry if ready else {}),(condition if ready else {}),(repairs if ready else ()))
